#!/bin/sh
#
# Run this script to rebuild the program used for fuzzing.
#
OBJ="sqlite3"
SRC="sqlite3.c shell.c"
FILES="$SRC sqlite3.h sqlite3ext.h"
ls -l $FILES
sha1sum $FILES
echo "Building from the files above...."
OPTS="$OPTS -DSQLITE_THREADSAFE=0"
OPTS="$OPTS -DSQLITE_OMIT_LOAD_EXTENSION"
OPTS="$OPTS -DSQLITE_NO_SYNC"
OPTS="$OPTS -DSQLITE_DEBUG"
OPTS="$OPTS -DSQLITE_OMIT_RANDOMNESS"
OPTS="$OPTS -DSQLITE_ENABLE_JSON1"
OPTS="$OPTS -DSQLITE_ENABLE_DBSTAT_VTAB"
OPTS="$OPTS -DSQLITE_ENABLE_FTS4"
OPTS="$OPTS -DSQLITE_ENABLE_FTS5"
OPTS="$OPTS -DSQLITE_ENABLE_GEOPOLY"
OPTS="$OPTS -DSQLITE_ENABLE_SELECTTRACE"
OPTS="$OPTS -DSQLITE_ENABLE_WHERETRACE"
OPTS="$OPTS -DSQLITE_ENABLE_MATH_FUNCTIONS"
OPTS="$OPTS -DSQLITE_HAVE_ZLIB=1"
OPTS="$OPTS -DHAVE_READLINE=0 -DHAVE_EDITLINE=0"
OPTS="$OPTS -DSQLITE_ENABLE_EXPLAIN_COMMENTS"
OPTS="$OPTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION"
OPTS="$OPTS -DSQLITE_ENABLE_STMTVTAB"
OPTS="$OPTS -DSQLITE_ENABLE_DBPAGE_VTAB"
OPTS="$OPTS -DSQLITE_ENABLE_DBSTAT_VTAB"
OPTS="$OPTS -DSQLITE_ENABLE_BYTECODE_VTAB"
OPTS="$OPTS -DSQLITE_ENABLE_OFFSET_SQL_FUNC"
../afl-gcc -Os -g -o $OBJ $OPTS -I. $SRC -ldl -lz -lm
ls -l $OBJ
gcc -Os -g -o $OBJ.gcc $OPTS -I. $SRC -ldl -lz -lm
ls -l $OBJ.gcc
